version: "3.9"

services:

  n8n:
    image: n8nio/n8n:latest
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_FUNCTION_ALLOW_EXTERNAL=*
    volumes:
      - n8n_data:/home/node/.n8n

  api:
    build: ./python-api
    ports:
      - "8000:8000"
    restart: always

  redis:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  n8n_data: